version: '3.8'
services:
  mcserver1:
    build: .
    container_name: mcserver1
    ports:
      - "25565:25565"
      - "19132:19132"
    tty: yes
    volumes:
      - ./server:/server
      - ./config:/config